### ISSUE TITLE
Build Error on Centos and OSX

### ISSUE THREAD

**Issue by dmfenton** [mraad/spark-gdb#1]
I wanted to play around with this and ran into a build error on Centos. Here are my logs. As a side note it would be nice to be able to simply download a jar.

```bash
Exception in thread "main" java.lang.NoClassDefFoundError: scala.collection.immutable.Vector
   at java.lang.Class.initializeClass(libgcj.so.10)
   at scala.collection.immutable.Vector$.<init>(Vector.scala:34)
   at scala.collection.immutable.Vector$.<clinit>(Vector.scala)
   at java.lang.Class.initializeClass(libgcj.so.10)
   at scala.package$.<init>(package.scala:78)
   at scala.package$.<clinit>(package.scala)
   at java.lang.Class.initializeClass(libgcj.so.10)
   at scala.Predef$.<init>(Predef.scala:90)
   at scala.Predef$.<clinit>(Predef.scala)
   at java.lang.Class.initializeClass(libgcj.so.10)
   at org.scalatest.time.Span$.org$scalatest$time$Span$$totalNanosForDoubleLength(Span.scala:643)
   at org.scalatest.time.Span.<init>(Span.scala:350)
   at org.scalatest.time.Span$.<init>(Span.scala:585)
   at org.scalatest.time.Span$.<clinit>(Span.scala)
   at java.lang.Class.initializeClass(libgcj.so.10)
   at org.scalatest.tools.Runner$.<init>(Runner.scala:779)
   at org.scalatest.tools.Runner$.<clinit>(Runner.scala)
   at java.lang.Class.initializeClass(libgcj.so.10)
   at org.scalatest.tools.Runner.main(Runner.scala)
Caused by: java.lang.ClassFormatError: scala.collection.parallel.immutable.ParVector (erroneous type descriptor)
   at java.lang.VMClassLoader.defineClass(libgcj.so.10)
   at java.lang.ClassLoader.defineClass(libgcj.so.10)
   at java.security.SecureClassLoader.defineClass(libgcj.so.10)
   at java.net.URLClassLoader.findClass(libgcj.so.10)
   at java.lang.ClassLoader.loadClass(libgcj.so.10)
   at java.lang.ClassLoader.loadClass(libgcj.so.10)
   at java.lang.Class.initializeClass(libgcj.so.10)
   ...18 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.310s
[INFO] Finished at: Sat Nov 12 17:58:19 EST 2016
[INFO] Final Memory: 23M/379M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.scalatest:scalatest-maven-plugin:1.0:test (test) on project spark-gdb_1.6.1: There are test failures -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.scalatest:scalatest-maven-plugin:1.0:test (test) on project spark-gdb_1.6.1: There are test failures
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures
	at org.scalatest.tools.maven.TestMojo.execute(TestMojo.java:107)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by dmfenton** [comment]
OSX

``` bash
Discovery starting.
Discovery completed in 612 milliseconds.
Run starting. Expected test count is: 20
SerDeSpec:
- should SerDe PointUDT
- should SerDe PointZUDT
- should SerDe PointMUDT
- should SerDe PointZMUDT
- should SerDe PolylineUDT
- should SerDe PolylineMUDT
- should SerDe PolygonUDT
SegmentIteratorSpec:
- should match no parts
- should match 0 parts
- should match 1 part with 1 segment
- should match 1 part with 2 segments
- should match 2 parts with 1 segment
- should match 2 parts with 3,2 segments
- should match 3 parts with 1,1,1 segments
GDBSuite:
18:07:10 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
- Points
- Lines
- MLines *** FAILED ***
  java.io.FileNotFoundException: File src/test/resources/Test.gdb/a00000011.gdbtable does not exist
  at org.apache.hadoop.fs.RawLocalFileSystem.getFileStatus(RawLocalFileSystem.java:520)
  at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:398)
  at org.apache.hadoop.fs.ChecksumFileSystem$ChecksumFSInputChecker.<init>(ChecksumFileSystem.java:137)
  at org.apache.hadoop.fs.ChecksumFileSystem.open(ChecksumFileSystem.java:339)
  at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:763)
  at com.esri.gdb.GDBTable$.apply(GDBTable.scala:51)
  at com.esri.gdb.GDBRelation.inferSchema(GDBRelation.scala:19)
  at com.esri.gdb.GDBRelation.<init>(GDBRelation.scala:13)
  at com.esri.gdb.package$SQLContextImplicits.gdbFile(package.scala:52)
  at com.esri.gdb.GDBSuite$$anonfun$3.apply$mcV$sp(GDBSuite.scala:100)
  ...
- Polygons *** FAILED ***
  java.io.FileNotFoundException: File src/test/resources/Test.gdb/a00000012.gdbtable does not exist
  at org.apache.hadoop.fs.RawLocalFileSystem.getFileStatus(RawLocalFileSystem.java:520)
  at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:398)
  at org.apache.hadoop.fs.ChecksumFileSystem$ChecksumFSInputChecker.<init>(ChecksumFileSystem.java:137)
  at org.apache.hadoop.fs.ChecksumFileSystem.open(ChecksumFileSystem.java:339)
  at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:763)
  at com.esri.gdb.GDBTable$.apply(GDBTable.scala:51)
  at com.esri.gdb.GDBRelation.inferSchema(GDBRelation.scala:19)
  at com.esri.gdb.GDBRelation.<init>(GDBRelation.scala:13)
  at com.esri.gdb.package$SQLContextImplicits.gdbFile(package.scala:52)
  at com.esri.gdb.GDBSuite$$anonfun$4.apply$mcV$sp(GDBSuite.scala:150)
  ...
- DDL test
- Field names, aliases and values
Run completed in 6 seconds, 265 milliseconds.
Total number of tests run: 20
Suites: completed 4, aborted 0
Tests: succeeded 18, failed 2, canceled 0, ignored 0, pending 0
*** 2 TESTS FAILED ***
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:19 min
[INFO] Finished at: 2016-11-12T18:07:16-05:00
[INFO] Final Memory: 33M/580M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.scalatest:scalatest-maven-plugin:1.0:test (test) on project spark-gdb_1.6.1: There are test failures -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by mraad** [comment]
Thanks for this - push the missing files - please try again

**Comment by dmfenton** [comment]
Works now 👍 Thanks @mraad!
